@startuml
class ConfigurationTemplateGenerator <<partial>> {
    + ConfigurationTemplateGenerator(encodingName:string, firstRow:IEnumerable<string>, headers:IEnumerable<string>)
}
class ColumnDefs {
    + Index : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
}
ConfigurationTemplateGenerator +-- ColumnDefs
class PropertyDefs {
    + Column : ColumnDefs <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Type : string <<get>> <<set>>
}
ConfigurationTemplateGenerator +-- PropertyDefs
@enduml
