@startuml
class MainWindowViewModel {
    + SelectedTab : int <<get>> <<set>>
    + SelectedTemplate : string <<get>> <<set>>
    + CurrentFilePath : string <<get>> <<set>>
    + CurrentFileName : string <<get>> <<set>>
    + CurrentConfigName : string <<get>> <<set>>
    + CsvRows : ObservableCollection<object> <<get>> <<set>>
    + ErrorMessages : ObservableCollection<string> <<get>> <<set>>
    + HasErrorMessages : bool <<get>> <<set>>
    + ConfigFileTemplates : ObservableCollection<string> <<get>>
    + ConfigurationDoc : IDocument <<get>> <<set>>
    + QueryDoc : IDocument <<get>> <<set>>
    + ReadCsvCommand : ICommand <<get>>
    + WriteCsvCommand : ICommand <<get>>
    + QueryCommand : ICommand <<get>>
    + ResetQueryCommand : ICommand <<get>>
    + RunConfigCommand : ICommand <<get>>
    + SaveConfigCommand : ICommand <<get>>
    + SaveConfigAsCommand : ICommand <<get>>
    + OpenConfigDirCommand : ICommand <<get>>
    + MainWindowViewModel(viewServiceProvider:IViewServiceProvider)
    + GetDataGridColumnValidation(propertyName:string) : DataGridColumnValidationRule
    + <<async>> GetCompletionListAsync(position:int, code:string) : Task<IEnumerable<CompletionData>>
    + GetDataGridColumnConverter(propertyName:string) : DataGridColumnConverter
    + Dispose() : void
}
BindableBase <|-- MainWindowViewModel
IDisposable <|-- MainWindowViewModel
@enduml
