@startuml
!include .\\App.xaml.puml
!include .\\Bindings\BindableBase.puml
!include .\\Bindings\DataGridColumnConverter.puml
!include .\\Bindings\DataGridColumnValidationRule.puml
!include .\\Bindings\DelegateCommand.puml
!include .\\Bindings\EncodingInfoToStringConverter.puml
!include .\\Bindings\ErrorNotificationBindableBase.puml
!include .\\Models\ColumnValidation.puml
!include .\\Models\CompletionData.puml
!include .\\Models\CsvConfigFileManager.puml
!include .\\Models\CsvEditSharpConfigurationHost.puml
!include .\\Models\CsvEditSharpWorkspace.puml
!include .\\Models\CustomBooleanConverter.puml
!include .\\Models\EnumerableExt.puml
!include .\\Models\GenerateConfigSettings.puml
!include .\\Models\ICsvEditSharpConfigurationHost.puml
!include .\\Models\RegisterClassMapTarget.puml
!include .\\Models\SaveConfigSettings.puml
!include .\\Services\GenerageConfigDialogService.puml
!include .\\Services\IFileSelectionService.puml
!include .\\Services\IModalDialogService.puml
!include .\\Services\IViewServiceProvider.puml
!include .\\Services\OpenFileDialogService.puml
!include .\\Services\SaveConfigDialogService.puml
!include .\\Services\SaveFileDialogService.puml
!include .\\Services\ViewServiceProvider.puml
!include .\\T4\ConfigurationTemplateGenerator.puml
!include .\\T4\ConfigurationTemplateGenerator.pertial.puml
!include .\\ViewModels\GenerateConfigDialogViewModel.puml
!include .\\ViewModels\MainWindowViewModel.puml
!include .\\ViewModels\SaveConfigDialogViewModel.puml
!include .\\Views\GenerateConfigDialog.xaml.puml
!include .\\Views\MainWindow.xaml.puml
!include .\\Views\SaveConfigDialog.xaml.puml
@enduml
