@startuml
interface ICsvEditSharpConfigurationHost {
    Encoding : Encoding <<get>> <<set>>
    ClassMapForReading : CsvClassMap <<get>>
    ClassMapForWriting : CsvClassMap <<get>>
    ColumnValidations : IDictionary<string, ColumnValidation> <<get>>
    RegisterClassMap() : void
    RegisterClassMap(propertyMapSetter:Action<CsvClassMap<T>>) : void
    RegisterClassMap(propertyMapSetter:Action<CsvClassMap<T>>, target:RegisterClassMapTarget) : void
    SetConfiguration(configurationSetter:Action<CsvConfiguration>) : void
    AddValidation(memberSelector:Expression<Func<TType, TMember>>, validation:Func<TMember, bool>, errorMessage:string) : void
    Query(query:Func<IEnumerable<T>, IEnumerable<T>>) : void
    Query(query:Action<IEnumerable<T>>) : void
}
@enduml
