@startuml
class GenerateConfigDialogService {
    + Result : GenerateConfigSettings <<get>>
    + ShowModal() : bool?
}
"IModalDialogService`1" "<GenerateConfigSettings>" <|-- GenerateConfigDialogService
@enduml
