@startuml
class ViewServiceProvider {
    + OpenFileSelectionService : IFileSelectionService <<get>>
    + SaveFileSelectionService : IFileSelectionService <<get>>
    + GenerateConfigDialogService : IModalDialogService<GenerateConfigSettings> <<get>>
    + SaveConfigDialogService : IModalDialogService<SaveConfigSettings> <<get>>
    + ConfigSettingsDialogService : IModalDialogService <<get>>
}
IViewServiceProvider <|-- ViewServiceProvider
@enduml
